spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ordermix?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  devtools:
    restart:
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.56.10
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 10
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
server:
  port: 10000

#RSA 加解密
auth:
  privateKey: MIIEvGQ3FsavKuI6669hlD6u9yfQjSSxAd0FdANn2Yzju3I9fCw/Z0vjWmigNPZzmIuPh4dBAHFR57TwbO0KeGw39tPcxGukTY3Ap4ChgDwy+hC4Ium0QsrvgLqugUWBqNCb+9kz1JGpsxw9hXGKm8tpq3WZeytnmEp6d4wTw2IJF0zQ+lw1xbJGZjSHPCraT2Z2sfrt2OTQjKYGZlQsi7kmoq1CF+PGLeK0epgHP/l/bSy+PifpU5XCH4ceOgn2wdkqiFvbIMq43x+/kGQUA8QwbIS8XtjqLCF6bOX+Cd+TAgRkeezYU+GpnTfxZHxRwEqRyFcTAgMBAAECggEBAMHRjR+eENeRaNyst/auip06/oTKYuCOLEOPsEvGpUomSb4+EoDl4TQ5SH/d2SXR/drvprjd5hh3j2Nvf70OJnF+P/XgWz+ttfZbAgu7+D5P6bg0wCnIn9FdzsdeCTARaLGXofNa3vUWH1BxAaznwI7zTg4e1bQGY/iBKiPSXC/0tSOdszp0rjrdRJ99aJiJXvdbQTRGM1H5R0pl8RFCSNlDuUPFkEF2YAYkT0nASRLhF8NbvXMgKNyPCUJfWOCi3O3rPbx9Z87LcTyP8+mphANTAKlKr+26irEX8MNiNpEKW6+G75ELpPTawYypngVUMXAj9Wsqv2JlmsANh4I6LKECgYEA73mTnQJEdfAgOGa640RcCNjgEqW8vbxumKuwRc5yhUIHNoANQyKRU9sTu+o9gjTlusIfYfnPuYj4gxuGsKqKjpZnrwh3OhgHpSISArykdKy40uY4yiZi0eW1uX2rFDzrfMbJDkteQDFkXA11C0pwsP7pnk4EwvCUI0fA2XclYC0CgYEA1oPm+z9i84W8f28B1lj1IhGd4Gblg7NgWvzbOh95elDWcWDCmfGrOfRefRLrVAf2R1iEuHq+8dqqgajsw60XoXlTKPiKZ5ojURxxZIl/nY6ASDRxI8Fqjm3m4+BYq3MamBk3oJpH+HpKefalocyORyOxpUfDDoip7EZaU1sL3D8CgYBFrrzTTRuardrSTqJHC1c0g9b/1hZLp48PAbZzOZV9TS9IHo69YEulePQPFCP9xWKrq1zyZ3yYYlDd5Z6Vvao/v2hAOFhpISDoXjebcETyZmgJhlA0EmNi7FKqvPSRGQD09+r9K9UrHLQ1TP0n4etUtXhJRi6Agvy4H2LwZIkNqQKBgQCHbNI/v66ais2Lrer9BUAMeA6xgoRW9sFX79X/BavNOoeHIEz6nwU4GzwjvfPvIu+p7woq5OLzENcf8CM5DWeju1JyxSWrbjXpmQlFLUDxmOsHqoPazNqWfG+NYS7ZXltltlXWAFB7X8jw4nOCh/8yjigybfGIlWKhFXEkuo/sRQKBgD4UBLxovLWkUrOky0YXbD8N1g/z5lqkpy1t/Dq4QuWt5YDFN1KDJL2TbaL494xOIOq3QKAKP5xI4dAiiIkoZmM5Bl8RZuAltxqiN7OePGgTLbRC+mKIfLtVOoGj0b2/maohE2Kb5rFRiHVRDNB5KQLvxXBuyuDpBHak9uSDGMEB

# 阿里云配置
aliyun:
  oss:
    access-key-id:  # 你的accessKeyId
    access-key-secret: #  你的accessKeySecret
    endpoint: # 你的endpoint
    bucket:  # 你的bucket
